
//! Personality tags

use strum::{Display, VariantArray};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Display, VariantArray)]
#[strum(serialize_all = "kebab-case")]
pub enum PersonalityTag {
  TimeTraveler,
  Dramatic,
  SoftSpoken,
  Optimistic,
  TeaObsessed,
  CoffeeObsessed,
  GodComplex,
  Monologuing,
  Incompetent,
  Undead,
  ExtremelyPolite,
  Royalty,
  Philosophical,
  Hustler,
  AlienInDisguise,
  AlwaysGetsLost,
  WantedByTheLaw,
  HasImaginaryFriend,
  OnlineDating,
  LovesPetNames,
  TalksLikeYoda,
  BadAtMath,
  JustGotFired,
  AlwaysOversleeps,
  HotHeaded,
  AirHeaded,
  OverusesEmoji,
  SpeaksInRiddles,
  LovesToRhyme,
  AlwaysSings,
  NeverFinishesSentences,
  BadlyDubbed,
  Overexplains,
  ExistentialDread,
  Paranoid,
  Skeptic,
  StuckInATimeLoop,
  RecentlyDefrostedFromCryoSleep,
  WorkingCustomerService,
  OnAQuest,
  TechSupport,
  TrappedInADream,
  StrandedAtSea,
  SecretlyAGhost,
  BadAtEnglish,
  AfraidOfEverything,
  OnParole,
  InWitnessProtection,
  DoesntGetSlang,
  Influencer,
  Insane,
  LiteralMinded,
  GoldfishMemory,
  PathologicalLiar,
  LovesPuns,
  BadGambler,
  ManiacalLaughter,
}
